# Generated by Django 3.2 on 2022-10-23 12:20

import datetime
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('booking_type', models.CharField(choices=[('Stag', 'Stag'), ('Adults', 'Adults'), ('Corporate', 'Corporate'), ('Teens', 'Teens'), ('School', 'School'), ('Splatball', 'Splatball')], max_length=30)),
                ('number_of_players', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)])),
                ('date_to_play', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('time_to_play', models.TimeField()),
            ],
        ),
    ]
